#! /bin/sh

sxhkd &

bspc monitor eDP1 -d I II III IV V VI VII VIII IX X
bspc monitor DP-1 -d 1 2 3

bspc config border_width     0
bspc config window_gap      20
bspc config top_padding     42
bspc config bottom_padding  42
bspc config right_padding   42
bspc config left_padding    42

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

# source the colors.
. "/home/brandon/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color0"
bspc config active_border_color "$color0"
bspc config focused_border_color "$color0"
bspc config presel_feedback_color "$color1"

#per window rules
bspc rule -a Zathura state=tiled
